### PR TITLE
[WIP ]A more current head of develop and Adam Lyon's changes + FNAL packages

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by hegner** [comment]
I believe the fnal repo things should go into a separate git project, no? Why not moving them to hep-spack?

**Comment by gartung** [comment]
This is a WIP pull request. I wanted to avoid a conflict with the root6 package that Brett created.

**Comment by hegner** [comment]
Thanks. I now called it a WIP :-)

**Comment by gartung** [comment]
The packages the Adam added require changes he made to the spack library. I decided to keep them together but not add the packages to the builtin package directory.

**Pull request closed without merging**
